// <auto-generated />
using System;
using Geekymon2.CarsApi.Cars.DAL.DataAccess.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Geekymon2.CarsApi.Cars.DAL.Migrations
{
    [DbContext(typeof(CarContext))]
    [Migration("20210417043226_updated entities")]
    partial class updatedentities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Geekymon2.CarsApi.Cars.DAL.DataAccess.Entities.Car", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Doors")
                        .HasColumnType("int");

                    b.Property<int?>("EngineID")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Odometer")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("EngineID");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("Geekymon2.CarsApi.Cars.DAL.DataAccess.Entities.Engine", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cylinders")
                        .HasColumnType("int");

                    b.Property<int>("Description")
                        .HasColumnType("int");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Engine");
                });

            modelBuilder.Entity("Geekymon2.CarsApi.Cars.DAL.DataAccess.Entities.Car", b =>
                {
                    b.HasOne("Geekymon2.CarsApi.Cars.DAL.DataAccess.Entities.Engine", "Engine")
                        .WithMany()
                        .HasForeignKey("EngineID");

                    b.Navigation("Engine");
                });
#pragma warning restore 612, 618
        }
    }
}
