variables:
  buildConfiguration: 'Release'

steps:
  - task: DockerCompose@@
    displayName: Build CarFinder API image
    inputs:
      action: Build services
      containerregistrytype: Docker Hub
      dockerComposeFile: docker-compose.yml
      projectName: $(Build.Repository.Name)