version: "3.9"
services: 
  web: 
    restart: always
    image: "geekymon2/carfinder"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db,${DB_PORT};Database=Cars;User Id=${DB_USER};Password=${DB_PASSWORD};    
    build: .
    #container runs on port 5000
    #container exposing port 8080 locally
    #container overrides APP_PORT when deployed
    ports:
      - "${APP_PORT:-8080}:5000"
    depends_on: 
      - db
  db:
    hostname: "db"
    restart: always
    image: "mcr.microsoft.com/mssql/server"
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${DB_PASSWORD:-P@ssw0rd}"
    #db container runs on port 1433
    #db container exposing port 1403 locally
    #db container overrides DB_PORT when deployed
    ports:
      - "${DB_PORT:-1403}:1433"
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${DOZZLE_PORT:-88}:8080