version: "3.9"
services: 
  web: 
    image: "geekymon2/carfinder"
    build: .
    #container runs on port 5000
    #container exposing port 80
    ports:
      - "80:5000"
    depends_on: 
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "P@ssw0rd"
    #db container keeps running on port 1433
    #exposing port 1403 to host db connection
    ports:
      - "1403:1433"