version: "3.9"
services: 
  web: 
    image: "geekymon2/carfinder"
    build: .
    ports:
      - "5000:5000"
    depends_on: 
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "P@ssw0rd"
    ports: 
      - "1403:1433"