namespace Geekymon2.CarsApi.Cars.DAL.DataAccess.Entities
{
    public enum Make
    {
        AUDI,
        BMW,
        FORD,
        HOLDEN,
        HYUNDAI,
        KIA,
        MAZDA,
        MERCEDESBENZ,
        MITSUBISHI,
        NISSAN,
        SUBARU,
        TOYOTA,
        VOLKSWAGEN,
        SUZUKI,
        HONDA,
        JEEP,
        LANDROVER,
        LEXUS,
        MAHINDRA,
        PORSCHE,
        SAAB,
        SKODA,
        TESLA,
        TATA,
        VOLVO,        
    }
}