steps:
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
   secretEnv: ['USERNAME', 'PASSWORD']
 - name: "gcr.io/cloud-builders/docker"
   entrypoint: 'bash'
   args: ['-c', 'docker run $$USERNAME/carfinder:latest']
   secretEnv: ['USERNAME']
availableSecrets:
  secretManager:
  - versionName: projects/802472575906/secrets/dockerhub-username/versions/1
    env: 'PASSWORD'
  - versionName: projects/802472575906/secrets/dockerhub-password/versions/1
    env: 'USERNAME'